### ISSUE TITLE
简单浏览似乎无法使用，找不到LLPhotoBrowserViewController

### ISSUE THREAD

**Issue by shevakuilin** [LvJianfeng/LLPhotoBrowser#1]
是否需要什么前置步骤，望说明

**Comment by LvJianfeng** [comment]
这个我已经用在生产上了，还请提供使用的代码片段截图哦。

发自我的 iPhone

**Comment by LvJianfeng** [comment]
@shevakuilin  还有哦，请确认已添加
```swift
import LLPhotoBrowser
```

**Comment by shevakuilin** [comment]
直接添加的class文件夹下的类，能否不通过LLPhotoBrowserViewController调用方法？

let browser = LLPhotoBrowserViewController.init(photoArray: images,
currentIndex: indexPath.row)// 警告找不到LLPhotoBrowserViewController

        // 模态弹出

 browser.presentBrowserViewController()

2017-04-20 22:46 GMT+08:00 Crazyf <notifications@github.com>:

**Comment by LvJianfeng** [comment]
@shevakuilin  不行，需要LLPhotoBrowserViewController进行初始化的，且当前工具库绑定了三方库Kingfisher

**Comment by shevakuilin** [comment]
如果我要使用，就需要引用整个LLPhotoBrowser吗

2017-04-21 12:02 GMT+08:00 Crazyf <notifications@github.com>:

**Comment by LvJianfeng** [comment]
你通过pod肯定是需要使用的import的，不然找不到呢

发自我的 iPhone
