### ISSUE TITLE
我想问下，数据源里面的“taobao”"百度"是在哪设置的

### ISSUE THREAD

**Issue by isennn** [LvJianfeng/LLPhotoBrowser#2]
为什么调用UIImage(named:"taobao")...他自动就识别到二维码的图片了。。感谢解答

**Comment by LvJianfeng** [comment]
@isennn  测试的图片都在```Assets.xcassets```里面的呢

**Comment by isennn** [comment]
大意了，没看到。。。刚才全局搜的时候没有，我以为从网络下载的 尴尬。。

**Comment by LvJianfeng** [comment]
嗯额，找到就行
