### ISSUE TITLE
显示加密图片

### ISSUE THREAD

**Issue by gushenmeiying** [LvJianfeng/LLPhotoBrowser#3]
显示加密图片时，如果在设置model的时候做图片解密操作太耗时间，所有选择在设置图片的时候做图片解密操作，故而需要重写`func loadBrowserImagerWithModel(item: LLBrowserModel, cell: LLBrowserCollectionViewCell, imageFrame: CGRect)`方法，所以需要公开该方法。

**Comment by LvJianfeng** [comment]
@gushenmeiying  可以，我给你加open
