### ISSUE TITLE
建议压缩下需要下载的部分

### ISSUE THREAD

**Issue by cwxatlm** [LvJianfeng/LLPhotoBrowser#4]
100多M啊大哥...,github虽然没锁网,但是有时候在git上下载速度还是很慢的,100多兆真的很难下载的,建议只保留核心代码,加点示例最好也要保持下载包不超过20M,10M以内最好,100多兆真的不利于推广,不希望你写的辛辛苦苦被这种下载问题挡住了

**Comment by LvJianfeng** [comment]
@cwxatlm  哈哈，谢谢指导，主要是gif太大，后面我压缩压缩。
