### ISSUE TITLE
快速浏览图片右问题

### ISSUE THREAD

**Issue by cwxatlm** [LvJianfeng/LLPhotoBrowser#5]
进入大图浏览模式时,你点击一下图片然后快速左右移动一下图片就会crash

断点定位崩溃

LLBrowserViewController.swift     line: 367

解决: 要先判断indexPath
 if let indexPath = collectView?.indexPath(for: cell) {
 NotificationCenter.default.removeObserver(self, name: NSNotification.Name.UIDeviceOrientationDidChange, object: nil)
...
把单机退出浏览模式的相关代码放里面
}

**Comment by LvJianfeng** [comment]
感谢指出错误，一会将更新CocoaPods，谢谢
