### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ZClee128** [LvJianfeng/LLPhotoBrowser#8]
在model里面除了有http，应该也有https的判断，希望有缩略图和大图的展示，而不是只有默认图

**Comment by LvJianfeng** [comment]
@ZClee128  当前判断只是判断图片数据url的格式，其中也包含https的哈，至于缩略图这个，我后面加进去。谢谢哈。

**Comment by ZClee128** [comment]
但是我刚刚看你的model里没有哦，我加上去的

**Comment by ZClee128** [comment]
缩略图那个你是做了，哈哈，我没看到你有那个方法sourceImageView，这个就可以展示缩略图了

**Comment by LvJianfeng** [comment]
@ZClee128 这个主要是记录cell上的imageview的图片及坐标位置呢。你说的缩略我没明白，不是数据型的缩略，有些公司是给两套数据的一套小图数据一套源数据呢

**Comment by ZClee128** [comment]
是的，我们是两套，这样就可以展示imageview的缩略图，然后再加载url的大图，所以我说实现了

**Comment by LvJianfeng** [comment]
@ZClee128 
喔喔 好的吧，那你可以先直接给sourceImageView传缩略图的数据。
回头我把model里加两个缩略图的参数就好了。
