### ISSUE TITLE
动画效果

### ISSUE THREAD

**Issue by ZClee128** [LvJianfeng/LLPhotoBrowser#9]
点击图片回到原来位子，会出现白色view，不知道是什么，这样体验不好

**Comment by LvJianfeng** [comment]
@ZClee128  你是说控制器吧？大图黑色消失那种突兀的感觉吧。

**Comment by ZClee128** [comment]
是白色的背景，一般应该设置成透明的比较好，但是我找不到是那个控制器

**Comment by LvJianfeng** [comment]
白色只有demo的控制器。

**Comment by ZClee128** [comment]
但是demo控制器是什么，我是pod进去的
